/* ============================================================================
 * stock-images.js — 홈페이지에 원래 들어 있는 사진 목록 (사진 모음 "사이트 기본 사진" 탭)
 *   생성: site/static/images/ 스캔 (@2x·@m 고해상도·모바일 변형은 제외 — 원본만).
 *   path = /static/... 규약 (cms-inject.js 경로 규약 5 · admin adminImageUrl 과 동일).
 *   label = 원장이 읽는 한국어 이름 (파일명 노출 금지), group = 묶음 제목.
 *   ⚠ 사진을 추가·삭제하면 이 목록도 함께 손봐 주세요 (빌드 스텝 없음 — 수기 관리).
 * ========================================================================== */
window.ZIA_STOCK_IMAGES = [
  { path: "/static/images/main/bg_section2.jpg", label: "홈 2번째 구역 배경", group: "홈 화면" },
  { path: "/static/images/main/bg_section3.jpg", label: "홈 3번째 구역 배경", group: "홈 화면" },
  { path: "/static/images/main/bg_section4.jpg", label: "홈 4번째 구역 배경", group: "홈 화면" },
  { path: "/static/images/main/bg_section5.jpg", label: "홈 5번째 구역 배경", group: "홈 화면" },
  { path: "/static/images/main/bg_section6.jpg", label: "홈 6번째 구역 배경", group: "홈 화면" },
  { path: "/static/images/main/bg_section7.jpg", label: "홈 7번째 구역 배경", group: "홈 화면" },
  { path: "/static/images/main/bg_section8.jpg", label: "홈 8번째 구역 배경", group: "홈 화면" },
  { path: "/static/images/main/bg_section9.jpg", label: "홈 9번째 구역 배경", group: "홈 화면" },
  { path: "/static/images/main/img_section3_img1.jpg", label: "홈 소개 사진 1", group: "홈 화면" },
  { path: "/static/images/main/img_section3_img2.jpg", label: "홈 소개 사진 2", group: "홈 화면" },
  { path: "/static/images/main/img_section3_img3.jpg", label: "홈 소개 사진 3", group: "홈 화면" },
  { path: "/static/images/main/img_section4_img1.png", label: "홈 안내 그림 1", group: "홈 화면" },
  { path: "/static/images/main/img_section4_img2.png", label: "홈 안내 그림 2", group: "홈 화면" },
  { path: "/static/images/main/img_section4_img3.png", label: "홈 안내 그림 3", group: "홈 화면" },
  { path: "/static/images/main/img_section5_img1.jpg", label: "홈 진료 소개 사진 1", group: "홈 화면" },
  { path: "/static/images/main/img_section5_tab_img1.jpg", label: "홈 진료탭 사진 1", group: "홈 화면" },
  { path: "/static/images/main/img_section5_tab_img2.jpg", label: "홈 진료탭 사진 2", group: "홈 화면" },
  { path: "/static/images/main/img_section5_tab_img3.jpg", label: "홈 진료탭 사진 3", group: "홈 화면" },
  { path: "/static/images/main/bg_main_visual.jpg", label: "홈 첫 화면 큰 배경 1", group: "홈 화면" },
  { path: "/static/images/main/bg_main_visual_2.jpg", label: "홈 첫 화면 큰 배경 2", group: "홈 화면" },
  { path: "/static/images/main/img_section6_img1.jpg", label: "홈 후기 구역 사진 1", group: "홈 화면" },
  { path: "/static/images/main/img_section6_img2.jpg", label: "홈 후기 구역 사진 2", group: "홈 화면" },
  { path: "/static/images/sub/bg_about_sct1_img1.jpg", label: "의원소개 1번째 구역 배경", group: "의원소개" },
  { path: "/static/images/sub/bg_about_sct1_img2.jpg", label: "의원소개 1번째 구역 배경 2", group: "의원소개" },
  { path: "/static/images/sub/bg_about_sct2_img1.jpg", label: "의원소개 2번째 구역 배경", group: "의원소개" },
  { path: "/static/images/sub/bg_about_sct3_img1.jpg", label: "의원소개 3번째 구역 배경", group: "의원소개" },
  { path: "/static/images/sub/img_clinic_sct5_img1.jpg", label: "진료 과정 사진 1", group: "진료 페이지" },
  { path: "/static/images/sub/img_clinic_sct5_img2.jpg", label: "진료 과정 사진 2", group: "진료 페이지" },
  { path: "/static/images/sub/img_clinic_sct5_img3.jpg", label: "진료 과정 사진 3", group: "진료 페이지" },
  { path: "/static/images/sub/img_clinic_sct5_img4.jpg", label: "진료 과정 사진 4", group: "진료 페이지" },
  { path: "/static/images/sub/img_clinic_sct5_img5.jpg", label: "진료 과정 사진 5", group: "진료 페이지" },
  { path: "/static/images/sub/img_clinic_sct2_img1.jpg", label: "진료 안내 사진 1", group: "진료 페이지" },
  { path: "/static/images/sub/img_clinic_sct2_img2.jpg", label: "진료 안내 사진 2", group: "진료 페이지" },
  { path: "/static/images/sub/img_clinic_sct2_img3.jpg", label: "진료 안내 사진 3", group: "진료 페이지" },
  { path: "/static/images/sub/img_clinic_sct2_img4.jpg", label: "진료 안내 사진 4", group: "진료 페이지" },
  { path: "/static/images/sub/img_clinic_sct2_img5.jpg", label: "진료 안내 사진 5", group: "진료 페이지" },
  { path: "/static/images/sub/bg_clinic_sct1_img1.jpg", label: "진료 페이지 1번째 구역 배경", group: "진료 페이지" },
  { path: "/static/images/sub/bg_clinic_sct2_img1.jpg", label: "진료 페이지 2번째 구역 배경", group: "진료 페이지" },
  { path: "/static/images/sub/bg_clinic_sct3_img1.jpg", label: "진료 페이지 3번째 구역 배경", group: "진료 페이지" },
  { path: "/static/images/sub/bg_clinic_sct4_img1.jpg", label: "진료 페이지 4번째 구역 배경", group: "진료 페이지" },
  { path: "/static/images/sub/bg_clinic_sct5_img1.jpg", label: "진료 페이지 5번째 구역 배경", group: "진료 페이지" },
  { path: "/static/images/sub/bg_clinic_sct6_img1.jpg", label: "진료 페이지 6번째 구역 배경", group: "진료 페이지" },
  { path: "/static/images/sub/bg_review_sct1_img1.jpg", label: "치료후기 1번째 구역 배경", group: "치료후기" },
  { path: "/static/images/sub/bg_review_sct2_img.jpg", label: "치료후기 2번째 구역 배경", group: "치료후기" },
  { path: "/static/images/sub/review_def.jpg", label: "후기 기본 사진", group: "치료후기" },
  { path: "/static/images/sub/review_sample1.jpg", label: "후기 예시 사진 1", group: "치료후기" },
  { path: "/static/images/sub/review_sample2.jpg", label: "후기 예시 사진 2", group: "치료후기" },
  { path: "/static/images/sub/review_sample3.jpg", label: "후기 예시 사진 3", group: "치료후기" },
  { path: "/static/images/sub/bg_faq_sct1_img1.jpg", label: "자주 묻는 질문 배경", group: "자주 묻는 질문" },
  { path: "/static/images/sub/bg_location_sct1_img1.jpg", label: "오시는 길 1번째 구역 배경", group: "오시는 길" },
  { path: "/static/images/sub/bg_location_sct2_img1.jpg", label: "오시는 길 2번째 구역 배경", group: "오시는 길" },
  { path: "/static/images/sub/bg_location_sct3_img1.jpg", label: "오시는 길 3번째 구역 배경", group: "오시는 길" },
  { path: "/static/images/sub/img_location_sct2.jpg", label: "오시는 길 사진", group: "오시는 길" },
  { path: "/static/images/common/gnb_towdepth.jpg", label: "메뉴 펼침 배경", group: "공통" },
  { path: "/static/images/common/bg_gnb_towdepth.jpg", label: "메뉴 펼침 배경(어두운 색)", group: "공통" },
  { path: "/static/images/sub/img_sct2_img1.jpg", label: "속지 사진 2-1", group: "공통" },
  { path: "/static/images/sub/img_sct3_img1.jpg", label: "속지 사진 3-1", group: "공통" },
  { path: "/static/images/sub/img_sct2_rightimg.png", label: "속지 장식 그림 2 (오른쪽)", group: "공통" },
  { path: "/static/images/sub/img_sct2_leftimg.png", label: "속지 장식 그림 2 (왼쪽)", group: "공통" },
  { path: "/static/images/sub/img_sct3_leftimg.png", label: "속지 장식 그림 3 (왼쪽)", group: "공통" }
];
